namespace EurekaMovieBE.Templates
{
    public class EmailTemplates
    {
        public const string RegistrationEmailTemplate =
            "<!DOCTYPE html>\n<html>\n\n<head>\n    <style>\n        * {\n            margin: 0;\n            padding: 0;\n            box-sizing: border-box;\n        }\n\n        body {\n            font-family: Arial, sans-serif;\n        }\n\n        .text-header {\n            font-size: 24px;\n            font-weight: bold;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n        .text-14-light {\n            font-size: 14px;\n            font-weight: normal;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n        .text-14-bold {\n            font-size: 14px;\n            font-weight: bold;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n        .frame {\n            width: 480px;\n            height: 360px;\n            border: 1px solid grey;\n            border-radius: 8px;\n            background-color: white;\n            min-width: 300px;\n            min-height: 360px;\n        }\n\n        .verify-button {\n            display: inline-block;\n            padding: 10px 20px;\n            text-decoration: none;\n            text-align: center;\n            font-size: 13px;\n            font-weight: bold;\n            color: black;\n            background-color: rgba(255, 204, 0, 1);\n            height: 36px;\n            width: 100%;\n            border-radius: 4px;\n            border: none;\n            box-shadow: 0.1px 0.1px 3px;\n            overflow-wrap: break-word;\n        }\n    </style>\n</head>\n\n<body style=\"display: flex; justify-content: center; align-items: center; flex-direction: row;\">\n    <div class=\"frame\" style=\"padding-left: 20px; padding-right: 20px;\">\n        <p class=\"text-header\" style=\"margin-top: 60px; margin-bottom: 20px;\">Hi {{UserName}},</p>\n        <p class=\"text-14-light\" style=\"margin-bottom: 20px;\">Click the button below to confirm your\n            registration to verify account.</p>\n        <a href=\"{{VerificationLink}}\" class=\"verify-button\" style=\"margin-bottom: 20px;\">Verify account</a>\n        <p class=\"text-14-light\" style=\"margin-bottom: 16px;\">If you did not request an account registration, simply\n            ignore this email. </p>\n        <p class=\"text-14-bold\" style=\"margin-bottom: 16px;\">Thank you,</p>\n        <p class=\"text-14-light\" style=\"margin-bottom: 20px;\">Film Bruh Inc.</p>\n    </div>\n</body>\n\n</html>";

        public const string ResetPasswordEmailTemplate =
            "<!DOCTYPE html><html>\n\n<head>\n    <style>\n        * {\n            margin: 0;\n            padding: 0;\n            box-sizing: border-box;\n        }\n\n        body {\n            font-family: Arial, sans-serif;\n        }\n\n        text-header {\n            font-size: 24px;\n            font-weight: bold;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n       .text-14-light {\n            font-size: 14px;\n            font-weight: normal;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n        .text-14-bold {\n            font-size: 14px;\n            font-weight: bold;\n            text-align: left;\n            color: rgba(0, 0, 0, 1);\n            overflow-wrap: break-word;\n        }\n\n        .frame {\n            width: 480px;\n            height: 360px;\n            border: 1px solid grey;\n            border-radius: 8px;\n            background-color: white;\n            min-width: 300px;\n            min-height: 360px;\n        }\n\n        .verify-button {\n            display: inline-block;\n            padding: 10px 20px;\n            text-decoration: none;\n            text-align: center;\n            font-size: 13px;\n            font-weight: bold;\n            color: black;\n            background-color: rgba(255, 204, 0, 1);\n            height: 36px;\n            width: 100%;\n            border-radius: 4px;\n            border: none;\n            box-shadow: 0.1px 0.1px 3px;\n            overflow-wrap: break-word;\n        }\n    </style>\n</head>\n\n<body style=\"display: flex; justify-content: center; align-items: center; flex-direction: row;\">\n    <div class=\"frame\" style=\"padding-left: 20px; padding-right: 20px;\">\n        <p class=\"text-header\" style=\"margin-top: 60px; margin-bottom: 20px;\">Your renew password code</p>\n        <p class=\"text-14-light\" style=\"margin-bottom: 20px;\">{{ResetToken}}</p> \n        <p class=\"text-14-light\" style=\"margin-bottom: 16px;\">If you did not request renew password, simply\n            ignore this email. </p>\n        <p class=\"text-14-bold\" style=\"margin-bottom: 16px;\">Thank you,</p>\n        <p class=\"text-14-light\" style=\"margin-bottom: 20px;\">Film Bruh Inc.</p>\n        </div>\n</body>\n\n</html>";
    }
}
